version: '3.5'

services:
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - '80:80'
        volumes:
            - ./code:/code
            - ./docker/nginx/vhost:/etc/nginx/conf.d/default.conf
        links:
            - php
            - mysql

    php:
        build:
            context: ./docker/php
        image: 'php:alpine'
        container_name: ${PROJECT_NAME}-php
        ports:
            - '9000:9000'
        volumes:
            - ./code:/code

    mysql:
        build:
            context: ./docker/mysql
        image: 'mysql:5.7'
        container_name: ${PROJECT_NAME}-mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '3306:3306'